### ISSUE TITLE
Warning when compiling project, clash with clojure.core/get

### ISSUE THREAD

**Issue by inolasco** [maxweber/clj-facebook-graph#7]
Hi

The following warning is generated when attempting to compile/run my project that uses clj-facebook-graph:

WARNING: get already refers to: #'clojure.core/get in namespace: clj-oauth2.client, being replaced by: #'clj-oauth2.client/get

Afterwards. running the application fails with the following exception:

Exception in thread "main" java.lang.NullPointerException, compiling:(auth.clj:1)
    at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3342)
    at clojure.lang.Compiler.compile1(Compiler.java:6985)
    at clojure.lang.Compiler.compile1(Compiler.java:6975)
    at clojure.lang.Compiler.compile(Compiler.java:7046)
    at clojure.lang.RT.compile(RT.java:385)
    at clojure.lang.RT.load(RT.java:425)
    at clojure.lang.RT.load(RT.java:398)
    at clojure.core$load$fn__4610.invoke(core.clj:5386)
    at clojure.core$load.doInvoke(core.clj:5385)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5200)
    at clojure.core$load_lib.doInvoke(core.clj:5237)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:602)
    at clojure.core$load_libs.doInvoke(core.clj:5271)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:604)
    at clojure.core$use.doInvoke(core.clj:5363)
    at clojure.lang.RestFn.invoke(RestFn.java:482)
    at kk_backend.controllers.facebook$loading__4505__auto__.invoke(facebook.clj:1)
    at clojure.lang.AFn.applyToHelper(AFn.java:159)
    at clojure.lang.AFn.applyTo(AFn.java:151)
    at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3337)
    at clojure.lang.Compiler.compile1(Compiler.java:6985)
    at clojure.lang.Compiler.compile1(Compiler.java:6975)
    at clojure.lang.Compiler.compile(Compiler.java:7046)
    at clojure.lang.RT.compile(RT.java:385)
    at clojure.lang.RT.load(RT.java:425)
    at clojure.lang.RT.load(RT.java:398)
    at clojure.core$load$fn__4610.invoke(core.clj:5386)
    at clojure.core$load.doInvoke(core.clj:5385)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5200)
    at clojure.core$compile$fn__4615.invoke(core.clj:5397)
    at clojure.core$compile.invoke(core.clj:5396)
    at user$eval27.invoke(NO_SOURCE_FILE:1)
    at clojure.lang.Compiler.eval(Compiler.java:6465)
    at clojure.lang.Compiler.eval(Compiler.java:6455)
    at clojure.lang.Compiler.eval(Compiler.java:6431)
    at clojure.core$eval.invoke(core.clj:2795)
    at clojure.main$eval_opt.invoke(main.clj:296)
    at clojure.main$initialize.invoke(main.clj:315)
    at clojure.main$null_opt.invoke(main.clj:348)
    at clojure.main$main.doInvoke(main.clj:426)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:405)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:518)
    at clojure.main.main(main.java:37)
Caused by: java.lang.NullPointerException
    at clojure.lang.Compiler$ObjExpr.emitVar(Compiler.java:4728)
    at clojure.lang.Compiler$DefExpr.emit(Compiler.java:395)
    at clojure.lang.Compiler.compile1(Compiler.java:6984)
    at clojure.lang.Compiler.compile(Compiler.java:7046)
    at clojure.lang.RT.compile(RT.java:385)
    at clojure.lang.RT.load(RT.java:425)
    at clojure.lang.RT.load(RT.java:398)
    at clojure.core$load$fn__4610.invoke(core.clj:5386)
    at clojure.core$load.doInvoke(core.clj:5385)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5200)
    at clojure.core$load_lib.doInvoke(core.clj:5237)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:602)
    at clojure.core$load_libs.doInvoke(core.clj:5271)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:602)
    at clojure.core$require.doInvoke(core.clj:5352)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clj_facebook_graph.auth$loading__4505__auto__.invoke(auth.clj:1)
    at clojure.lang.AFn.applyToHelper(AFn.java:159)
    at clojure.lang.AFn.applyTo(AFn.java:151)
    at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3337)
    ... 48 more

Any insights?

**Comment by eraad** [comment]
I'm having the same issue, trying to compile and get this error:

WARNING: get already refers to: #'clojure.core/get in namespace: clj-oauth2.client, being replaced by: #'clj-oauth2.client/get
Exception in thread "main" java.lang.NullPointerException, compiling:(auth.clj:1)
    at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3342)
    at clojure.lang.Compiler.compile1(Compiler.java:6985)
    at clojure.lang.Compiler.compile1(Compiler.java:6975)
    at clojure.lang.Compiler.compile(Compiler.java:7046)
    at clojure.lang.RT.compile(RT.java:385)
    at clojure.lang.RT.load(RT.java:425)
    at clojure.lang.RT.load(RT.java:398)
    at clojure.core$load$fn__4610.invoke(core.clj:5386)
    at clojure.core$load.doInvoke(core.clj:5385)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5200)
    at clojure.core$load_lib.doInvoke(core.clj:5237)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:602)
    at clojure.core$load_libs.doInvoke(core.clj:5271)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:604)
    at clojure.core$use.doInvoke(core.clj:5363)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at william.core$loading__4505__auto__.invoke(core.clj:1)
    at clojure.lang.AFn.applyToHelper(AFn.java:159)
    at clojure.lang.AFn.applyTo(AFn.java:151)
    at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3337)
    at clojure.lang.Compiler.compile1(Compiler.java:6985)
    at clojure.lang.Compiler.compile1(Compiler.java:6975)
    at clojure.lang.Compiler.compile(Compiler.java:7046)
    at clojure.lang.RT.compile(RT.java:385)
    at clojure.lang.RT.load(RT.java:425)
    at clojure.lang.RT.load(RT.java:398)
    at clojure.core$load$fn__4610.invoke(core.clj:5386)
    at clojure.core$load.doInvoke(core.clj:5385)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5200)
    at clojure.core$compile$fn__4615.invoke(core.clj:5397)
    at clojure.core$compile.invoke(core.clj:5396)
    at user$eval7.invoke(NO_SOURCE_FILE:1)
    at clojure.lang.Compiler.eval(Compiler.java:6465)
    at clojure.lang.Compiler.eval(Compiler.java:6455)
    at clojure.lang.Compiler.eval(Compiler.java:6431)
    at clojure.core$eval.invoke(core.clj:2795)
    at clojure.main$eval_opt.invoke(main.clj:296)
    at clojure.main$initialize.invoke(main.clj:315)
    at clojure.main$null_opt.invoke(main.clj:348)
    at clojure.main$main.doInvoke(main.clj:426)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:405)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:518)
    at clojure.main.main(main.java:37)
Caused by: java.lang.NullPointerException
    at clojure.lang.Compiler$ObjExpr.emitVar(Compiler.java:4728)
    at clojure.lang.Compiler$DefExpr.emit(Compiler.java:395)
    at clojure.lang.Compiler.compile1(Compiler.java:6984)
    at clojure.lang.Compiler.compile(Compiler.java:7046)
    at clojure.lang.RT.compile(RT.java:385)
    at clojure.lang.RT.load(RT.java:425)
    at clojure.lang.RT.load(RT.java:398)
    at clojure.core$load$fn__4610.invoke(core.clj:5386)
    at clojure.core$load.doInvoke(core.clj:5385)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5200)
    at clojure.core$load_lib.doInvoke(core.clj:5237)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:602)
    at clojure.core$load_libs.doInvoke(core.clj:5271)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:602)
    at clojure.core$require.doInvoke(core.clj:5352)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clj_facebook_graph.auth$loading__4505__auto__.invoke(auth.clj:1)
    at clojure.lang.AFn.applyToHelper(AFn.java:159)
    at clojure.lang.AFn.applyTo(AFn.java:151)
    at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3337)
    ... 48 more
Compilation failed.
